TickUp/Controllers/EventoController.cs
using Microsoft.AspNetCore.Mvc;
using TickUp.Models;

using FireSharp;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Newtonsoft.Json;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Runtime.ConstrainedExecution;
using System.Security.Cryptography;
using System.IO;
using Microsoft.Extensions.Primitives;
using HtmlAgilityPack;


namespace TickUp.Controllers
{
    public class EventoController : Controller
    {
        [ServiceFilter(typeof(Autentificacao))]
        public IActionResult CriarEvento()
        {
            return View();
        }
        [ServiceFilter(typeof(Autentificacao))]
        public IActionResult MostrarEvento()
        {
       
            return View();
        }

        [HttpPost]

        public IActionResult CriarEvento(string assuntoEvento, string categoriaEvento, string nomeEvento, string emailContato, string observacoes, string horarioInicio, string horarioTermino, string cpf, string email, DateOnly dataInicio, DateOnly dataTermino, int capacidade, string nomeLocal, string cep, string rua, string numero, string complemento, string bairro, string estado, string cidade,double valorIngresso)
        {



            foreach (IFormFile arq in Request.Form.Files){
                
                MemoryStream stream = new MemoryStream();
                arq.CopyTo(stream);
                byte[] bytesImagem = stream.ToArray();
                Evento evento = new Evento(
                        assuntoEvento,
                        categoriaEvento,
                        nomeEvento,
                        emailContato,
                        observacoes,
                        horarioInicio,
                        horarioTermino,
                        cpf,
                        email,
                        dataInicio,
                        dataTermino,
                        capacidade,
                        bytesImagem,
                        nomeLocal,
                        cep,
                        rua,
                        numero,
                        complemento,
                        bairro,
                        estado,
                        cidade,
                        valorIngresso
                        );

                TempData["msg"] = evento.Inserir(HttpContext);


                string idEvento = evento.ObterUltimoIdEvento();
               
                    for (int i = 0; i != capacidade; i++)
                    {
                        string idIngresso = Guid.NewGuid().ToString();

                    SetResponse response = client.Set(idEvento + "/" + idIngresso, evento);
                        if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        {

                        }
                    }
            
                }


            return RedirectToAction("CriarEvento");
        }

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "8bk6pzt4StGLmyg1h2ckiaODULn273DLyUeDeB7I",
            BasePath = "https://tickup-251a6-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;
        public EventoController()
        {
            try
            {
                client = new FireSharp.FirebaseClient(config);

            }
            catch (Exception)
            {

            }
        }
      



    }

}

TickUp/Controllers/IngressoController.cs
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Newtonsoft.Json;
using System.Collections.Generic;
using TickUp.Models;

namespace TickUp.Controllers
{
    public class IngressoController : Controller
    {

        [ServiceFilter(typeof(Autentificacao))]
        public IActionResult PegarIngresso()
        {
            return View();
        }

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "8bk6pzt4StGLmyg1h2ckiaODULn273DLyUeDeB7I",
            BasePath = "https://tickup-251a6-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;
        public IngressoController()
        {
            try
            {
                client = new FireSharp.FirebaseClient(config);
            }
            catch (Exception)
            {
                // Handle exception
            }
        }

        [HttpGet]
        public ActionResult PegarIngresso(string idEvento, int quantidadeIngresso)
        {
            FirebaseResponse response = client.Get(idEvento);

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                Dictionary<string, Ingresso> ingressosDic = JsonConvert.DeserializeObject<Dictionary<string, Ingresso>>(response.Body);
                int ingressosRestantes = ingressosDic.Count;

                if (ingressosRestantes < quantidadeIngresso)
                {
                    TempData["msg"] = "Não há ingressos suficientes disponíveis.";
                    return RedirectToAction("MostrarEvento", "Home", new { id = idEvento });

                }
                else
                {
                    int count = 0;
                    foreach (var ingresso in ingressosDic)
                    {
                        if (count >= quantidadeIngresso)
                        {
                            break;
                        }

                        string idIngresso = ingresso.Key;
                        string mensagem = new Ingresso().IngressoComprado(idEvento, idIngresso, HttpContext);

                        if (mensagem == "Comprado com sucesso")
                        {
                            client.Delete($"{idEvento}/{idIngresso}");
                            count++;
                        }
                        else
                        {
                            TempData["msg"] = mensagem;
                            return RedirectToAction("Login", "Usuario");
                        }
                    }
   
                    return RedirectToAction("Index", "Home");
                }
            }
          
            return RedirectToAction("MostrarEvento", "Evento");
        }



        public IActionResult IngressosComprados()
        {
            Ingresso ingresso = new Ingresso();


            List<Evento> eventos = ingresso.ListarIngressos(HttpContext);

            return View(eventos);
        }





    }
}

TickUp/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TickUp.Models;

namespace TickUp.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Cadastrar()
        {
            if (TempData.ContainsKey("msg"))
            {
                ViewBag.Message = TempData["msg"];
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(string emailUser, string cpfUser, string nomeUser, string senhaUser, string telefoneUser, int idadeUser)
        {
            Usuario user = new Usuario(emailUser, cpfUser, nomeUser, senhaUser, telefoneUser, idadeUser);
            TempData["msg"] = user.InserirUsuario();
            return RedirectToAction("Cadastrar");
        }

        public IActionResult Login()
        {
            if (TempData.ContainsKey("msg"))
            {
                ViewBag.Message = TempData["msg"];
            }
            return View();
        }

        [HttpPost]
        public IActionResult Login(string emailUser, string cpfUser, string nomeUser, string senhaUser)
        {
            Usuario usuario = new Usuario(emailUser, cpfUser, nomeUser, senhaUser, "", 0);

            bool loginBemSucedido = Usuario.Login(usuario);

            if (loginBemSucedido)
            {
                HttpContext.Session.SetString("user", JsonConvert.SerializeObject(usuario));
                Response.Cookies.Append("user", JsonConvert.SerializeObject(usuario),
                new CookieOptions()
                {
                    Expires = DateTime.Now.AddHours(1)
                });
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["msg"] = "Email ou senha incorreto";
                return RedirectToAction("Login");
            }
        }


        public IActionResult Logout()
        {
            var userSession = HttpContext.Session.GetString("user");

            if (userSession != null)
            {
                Usuario sairUsuario = JsonConvert.DeserializeObject<Usuario>(userSession);

                HttpContext.Session.Remove("user");

                //deslogando os cookies
                Response.Cookies.Delete("user");
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

TickUp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TickUp</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poetsen+One&display=swap" rel="stylesheet">

</head>
<body>

    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-ticket-perforated" viewBox="0 0 16 16">
                    <path d="M4 4.85v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9z" />
                    <path d="M1.5 3A1.5 1.5 0 0 0 0 4.5V6a.5.5 0 0 0 .5.5 1.5 1.5 0 1 1 0 3 .5.5 0 0 0-.5.5v1.5A1.5 1.5 0 0 0 1.5 13h13a1.5 1.5 0 0 0 1.5-1.5V10a.5.5 0 0 0-.5-.5 1.5 1.5 0 0 1 0-3A.5.5 0 0 0 16 6V4.5A1.5 1.5 0 0 0 14.5 3zM1 4.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v1.05a2.5 2.5 0 0 0 0 4.9v1.05a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-1.05a2.5 2.5 0 0 0 0-4.9z" />
                </svg>
                <h1 id="titulo">TickUp</h1>
            </a>
          <ul class="nav nav-pills">
    <li class="nav-item">
        <a asp-controller="Evento" asp-action="CriarEvento" id="nav-link" class="nav-link">Criar evento</a>
    </li>
</ul>

<div class="text-end">
                @if (Context.Session.GetString("user") == null)
                {
                    <a asp-controller="Usuario" asp-action="Login">
                        <button type="button" id="btn" class="btn btn-outline-primary me-2">Entrar</button>
                    </a>
                    <a asp-controller="Usuario" asp-action="Cadastrar">
                        <button type="button" id="btn" class="btn btn-primary">Cadastrar</button>
                    </a>
                }
                else
                {
                    <div class="menuVertical" style="position: relative;">
                        <svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#999999"><path d="M234-276q51-39 114-61.5T480-360q69 0 132 22.5T726-276q35-41 54.5-93T800-480q0-133-93.5-226.5T480-800q-133 0-226.5 93.5T160-480q0 59 19.5 111t54.5 93Zm246-164q-59 0-99.5-40.5T340-580q0-59 40.5-99.5T480-720q59 0 99.5 40.5T620-580q0 59-40.5 99.5T480-440Zm0 360q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q53 0 100-15.5t86-44.5q-39-29-86-44.5T480-280q-53 0-100 15.5T294-220q39 29 86 44.5T480-160Zm0-360q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17Zm0-60Zm0 360Z" /></svg>

                        <div id="listaItens" style="display: none; position: absolute; top: 40px; left: 0;">
                           
                            <ul class="list-group">
                                <li class="list-group-item">Meus Eventos</li>
                                <a asp-controller="Ingresso" asp-action="IngressosComprados">
                                <li class="list-group-item">Meus Ingressos</li></a>
                                <a asp-controller="Usuario" asp-action="Logout">
                                <li class="list-group-item">Sair</li></a>
                            </ul>
                        </div>
                    </div>

                    <script>
                        
                        document.addEventListener('DOMContentLoaded', function () {
                            var svgImagem = document.querySelector('svg[fill="#999999"]');
                            svgImagem.addEventListener('click', function () {
                               
                                var listaItens = document.getElementById('listaItens');
                                
                                if (listaItens.style.display === 'none') {
                                    listaItens.style.display = 'block';
                                } else {
                                    listaItens.style.display = 'none';
                                }
                            });
                        });
                    </script>


                }

               
</div>
        </header>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="container d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-ticket-perforated" viewBox="0 0 16 16">
                    <path d="M4 4.85v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9zm-7 1.8v.9h1v-.9zm7 0v.9h1v-.9z" />
                    <path d="M1.5 3A1.5 1.5 0 0 0 0 4.5V6a.5.5 0 0 0 .5.5 1.5 1.5 0 1 1 0 3 .5.5 0 0 0-.5.5v1.5A1.5 1.5 0 0 0 1.5 13h13a1.5 1.5 0 0 0 1.5-1.5V10a.5.5 0 0 0-.5-.5 1.5 1.5 0 0 1 0-3A.5.5 0 0 0 16 6V4.5A1.5 1.5 0 0 0 14.5 3zM1 4.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v1.05a2.5 2.5 0 0 0 0 4.9v1.05a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-1.05a2.5 2.5 0 0 0 0-4.9z" />
                </svg>
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Cyber Squad</span>
        </div>
    </footer> 

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TickUp/Views/Shared/_Toast.cshtml
@if (TempData["msg"] != null)
{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        if (@TempData["msg"].ToString().IndexOf("sucesso") > 0)
            toastr.success('@TempData["msg"]');
        else
            toastr.error('@TempData["msg"]');
    </script>
}